# Generated by Django 2.2.16 on 2022-10-13 00:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('1a4e16d6-0796-44fd-864e-ccfbcdab7e9f'), editable=False),
        ),
    ]
